Code1964/World-Voyage

project/templates/index.html
=> fix index.html

.gitignore
関連する issue: #<issue_number>
PULL_REQUEST_TEMPLATE copy.mdという謎のファイルが有ったので削除した。
=> remove: PULL_REQUEST_TEMPLATE copy.md

README.md
=> update: gitの使い方とdockerの使い方

README.md
=> README.mdに変更追加

project/templates/layout.html
関連する issue: #12 
ファビコンのやり方が分かりませんでした。
=> header changed

project/static/css/sample.css, project/templates/layout.html, project/templates/timeline.html
関連する issue: #11 
timeline,htmlに年代のボタンを作りました。cssでボタンのデザインを変えました。layout.htmlの設定で文章が自動中央寄せになっていたので、左寄せにしました。国・地域の方の処理がどうすればいいのか分かりませんでした。
=> timeline,css,layout changed

project/app.py, project/controllers/map_controller.py, project/static/css/sample.css, project/static/js/googleMap.js, project/templates/event.html, project/templates/index.html, project/templates/layout.html, project/templates/map.html, project/templates/summary.html, project/templates/timeline.html
関連する issue: #14 
map.htmlに地図を表示するために、javascriptを追加した。
.envファイルを読み込むために、バックエンド側も操作した。
=> add: google maps APIにてマップを出力した

README.md
=> fix: りーどみーの誤字を修正

README.md, project/app.py, project/controllers/login_controller.py, project/controllers/logout_controller.py, project/controllers/register_controller.py, project/templates/summary.html
=> add: ユーザー登録機能の雛形を追加

project/static/css/sample.css, project/static/dist/css/output.css, project/templates/index.html, project/templates/layout.html
=> add: index装飾

project/templates/index.html
=> index.htmlの写真・説明文追加

project/templates/country_info.html
=> fix: country_info.htmlで要素がないのにh1タグを出力していたのでそれを修正

project/static/js/googleMap.js
位置情報を取得できたときに、現在地の位置情報が消えないように変更
=> fix: map.htmlの細かい処理を変更(位置情報を取得できた場合のピンを消えないようにした)

project/static/css/sample.css, project/static/dist/css/output.css, project/static/js/googleMap.js, project/templates/map.html
関連する issue: #53 
map.htmlの表示を変更しました。
サイドバーの表示を変更しました。
場所検索ができるフォームを作成しました。
=> fix: map.html見た目を変更&サイドバー表示形式を大幅変更&国だけでなく場所の名前からも検索できるようにした

Dockerfile, controllers/flashcard_controller.py, controllers/map_controller.py, main.py, static/dist/css/output.css, templates/country_info.html, templates/flashcard.html, templates/layout.html
=> fix: mapで例外処理を追加

Dockerfile
=> fix: Dockerがビルドできない問題を修正

controllers/country_info_controller.py
=> fix: mapからcountryInfoに飛ぶ際にundefinedとなっていたときの処理を修正

controllers/flashcard_controller.py, static/dist/css/output.css, templates/flashcard.html, templates/region_info.html
=> fix: flash cardのimage欄を削除

static/css/sample.css, static/js/googleMap.js, templates/map.html
=> fix: 画面サイズも考慮して見やすいUIに変更した

controllers/region_info_controller.py, templates/index.html
=> add: indexから直接region_infoに飛べるように変更

templates/index.html
=> fix: index to region_infoで何も選択せずに情報を見るボタンを押した場合の処理

templates/layout.html
=> fix: リファクタリング(不要なjs読み込みを削除)

static/js/googleMap.js
=> fix: 重複している処理をFunction化した

controllers/region_info_controller.py, static/js/googleMap.js, templates/map.html, templates/region_info.html
=> add: region_infoで国名以外を調べたときにその都道府県がある国を表示する処理を追加

controllers/region_info_controller.py, templates/region_info.html
=> fix: indexからregion_infoに飛べなかったバグを修正

controllers/change_password_controller.py, controllers/login_controller.py, controllers/logout_controller.py, controllers/register_controller.py, static/js/googleMap.js
=> fix: 表示される文字をよりわかりやすくするように変更

static/dist/css/output.css
=> fix: 反映されてなかったTailwindを追加

static/dist/css/output.css, templates/apology.html, templates/change_password.html, templates/login.html, templates/region_info.html, templates/register.html, templates/usage.html
=> fix: titleの名前を日本語に変更

templates/region_info.html
=> update: 文字の大きさを変更

templates/layout.html, templates/note.html
=> change: 日本語化に合わせる
